In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10)

In [5]:
np.arange(1,10,2)

In [13]:
np.arange(1,10,0.5,dtype=np.float64)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [14]:
ds=np.arange(1,10,2)
ds.ndim

1

In [16]:
ds.shape

(5,)

In [19]:
ds.dtype

dtype('int32')

In [20]:
ds.itemsize

4

In [23]:
%%capture timeit_results
%timeit python_list_1 = range(1,1000)
%timeit python_list_1 = np.arange(1,1000)

In [24]:
print (timeit_results)

The slowest run took 9.14 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 562 ns per loop
The slowest run took 8.88 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.79 us per loop



In [25]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [27]:
np.array([[1,2],[2,3],[4,5]])

array([[1, 2],
       [2, 3],
       [4, 5]])

In [37]:
np.zeros([3,4,2],dtype=np.int64)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]], dtype=int64)

In [39]:
np.linspace(1,2)

array([ 1.        ,  1.02040816,  1.04081633,  1.06122449,  1.08163265,
        1.10204082,  1.12244898,  1.14285714,  1.16326531,  1.18367347,
        1.20408163,  1.2244898 ,  1.24489796,  1.26530612,  1.28571429,
        1.30612245,  1.32653061,  1.34693878,  1.36734694,  1.3877551 ,
        1.40816327,  1.42857143,  1.44897959,  1.46938776,  1.48979592,
        1.51020408,  1.53061224,  1.55102041,  1.57142857,  1.59183673,
        1.6122449 ,  1.63265306,  1.65306122,  1.67346939,  1.69387755,
        1.71428571,  1.73469388,  1.75510204,  1.7755102 ,  1.79591837,
        1.81632653,  1.83673469,  1.85714286,  1.87755102,  1.89795918,
        1.91836735,  1.93877551,  1.95918367,  1.97959184,  2.        ])

In [42]:
np.linspace(1,4,num=3)

array([ 1. ,  2.5,  4. ])

In [46]:
data_set=np.random.random((2,3))
data_set

array([[ 0.29268055,  0.13815002,  0.91969827],
       [ 0.39999544,  0.00278687,  0.02829351]])

In [47]:
np.max(data_set)

0.91969826546566436

In [52]:
np.max(data_set,axis=0)
# axis=0 column wise,if 1 row wise

array([ 0.39999544,  0.13815002,  0.91969827])

In [53]:
np.max(data_set,axis=1)

array([ 0.91969827,  0.39999544])

In [48]:
np.min(data_set)

0.0027868665719287256

In [54]:
np.mean(data_set)

0.29693410720303243

In [55]:
np.median(data_set)

0.21541528433069324

In [57]:
np.std(data_set,dtype=np.float32)

0.31154928

In [58]:
np.reshape(data_set,(3,2))

array([[ 0.29268055,  0.13815002],
       [ 0.91969827,  0.39999544],
       [ 0.00278687,  0.02829351]])

In [60]:
np.reshape(data_set,(6,1))

array([[ 0.29268055],
       [ 0.13815002],
       [ 0.91969827],
       [ 0.39999544],
       [ 0.00278687],
       [ 0.02829351]])

In [61]:
np.reshape(data_set,(6))

array([ 0.29268055,  0.13815002,  0.91969827,  0.39999544,  0.00278687,
        0.02829351])

In [62]:
#ravel also flatens the data set.Same as the above operation
np.ravel(data_set)

array([ 0.29268055,  0.13815002,  0.91969827,  0.39999544,  0.00278687,
        0.02829351])

In [68]:
data_set=np.random.random((5,10))
data_set

array([[ 0.18143145,  0.50107562,  0.13843291,  0.19711021,  0.61869979,
         0.91311048,  0.80688947,  0.69573915,  0.26047528,  0.37303549],
       [ 0.37740536,  0.70708848,  0.57690628,  0.80325707,  0.88400845,
         0.28271378,  0.68928768,  0.74103528,  0.40887046,  0.32018447],
       [ 0.73169129,  0.03248543,  0.67059703,  0.13476584,  0.11158901,
         0.56207675,  0.36445826,  0.02644161,  0.39812685,  0.83083828],
       [ 0.29748817,  0.72792128,  0.91164242,  0.87106165,  0.07300732,
         0.56461775,  0.56280869,  0.75827446,  0.20286767,  0.17784122],
       [ 0.04393692,  0.68107036,  0.97060041,  0.14448867,  0.6262384 ,
         0.52651722,  0.21681024,  0.31165539,  0.11894888,  0.25603626]])

In [69]:
data_set[1]

array([ 0.37740536,  0.70708848,  0.57690628,  0.80325707,  0.88400845,
        0.28271378,  0.68928768,  0.74103528,  0.40887046,  0.32018447])

In [70]:
data_set[1,0]

0.37740535503949468

In [71]:
data_set[2:4]

array([[ 0.73169129,  0.03248543,  0.67059703,  0.13476584,  0.11158901,
         0.56207675,  0.36445826,  0.02644161,  0.39812685,  0.83083828],
       [ 0.29748817,  0.72792128,  0.91164242,  0.87106165,  0.07300732,
         0.56461775,  0.56280869,  0.75827446,  0.20286767,  0.17784122]])

In [72]:
data_set[2:4,0]

array([ 0.73169129,  0.29748817])

In [73]:
data_set[2:4,0:2]

array([[ 0.73169129,  0.03248543],
       [ 0.29748817,  0.72792128]])

In [75]:
data_set[::]

array([[ 0.18143145,  0.50107562,  0.13843291,  0.19711021,  0.61869979,
         0.91311048,  0.80688947,  0.69573915,  0.26047528,  0.37303549],
       [ 0.37740536,  0.70708848,  0.57690628,  0.80325707,  0.88400845,
         0.28271378,  0.68928768,  0.74103528,  0.40887046,  0.32018447],
       [ 0.73169129,  0.03248543,  0.67059703,  0.13476584,  0.11158901,
         0.56207675,  0.36445826,  0.02644161,  0.39812685,  0.83083828],
       [ 0.29748817,  0.72792128,  0.91164242,  0.87106165,  0.07300732,
         0.56461775,  0.56280869,  0.75827446,  0.20286767,  0.17784122],
       [ 0.04393692,  0.68107036,  0.97060041,  0.14448867,  0.6262384 ,
         0.52651722,  0.21681024,  0.31165539,  0.11894888,  0.25603626]])

In [76]:
data_set[::2]

array([[ 0.18143145,  0.50107562,  0.13843291,  0.19711021,  0.61869979,
         0.91311048,  0.80688947,  0.69573915,  0.26047528,  0.37303549],
       [ 0.73169129,  0.03248543,  0.67059703,  0.13476584,  0.11158901,
         0.56207675,  0.36445826,  0.02644161,  0.39812685,  0.83083828],
       [ 0.04393692,  0.68107036,  0.97060041,  0.14448867,  0.6262384 ,
         0.52651722,  0.21681024,  0.31165539,  0.11894888,  0.25603626]])

In [79]:
data_set[2:4]

array([[ 0.73169129,  0.03248543,  0.67059703,  0.13476584,  0.11158901,
         0.56207675,  0.36445826,  0.02644161,  0.39812685,  0.83083828],
       [ 0.29748817,  0.72792128,  0.91164242,  0.87106165,  0.07300732,
         0.56461775,  0.56280869,  0.75827446,  0.20286767,  0.17784122]])

In [80]:
data_set[2:4,::2]

array([[ 0.73169129,  0.67059703,  0.11158901,  0.36445826,  0.39812685],
       [ 0.29748817,  0.91164242,  0.07300732,  0.56280869,  0.20286767]])